import { Restaurant } from './types';

export const RESTAURANTS: Restaurant[] = [
  {
    id: '1',
    name: '홀리어스 뷔페',
    category: '기타',
    signatureMenu: '호텔 뷔페 코너',
    description: '가성비와 퀄리티를 모두 잡은 호텔 뷔페로, 특별한 날이나 외빈 접대에 최적화된 공간입니다.',
    locationInfo: '본사 정문 기준 도보 8분, 홀리어스 호텔 내 위치',
    parking: '호텔 주차장 이용 가능',
    groupSeats: true,
    reservation: true,
    employeeReview: "나주에서 이만한 뷔페 찾기 힘들죠. 외빈 모실 때 실패 없는 선택입니다.",
    tags: ['외빈접대', '기념일', '호텔뷔페'],
    priceRange: '2~5만원',
    naverMapUrl: 'https://map.naver.com/v5/search/나주 홀리어스 뷔페'
  },
  {
    id: '2',
    name: '부영식당',
    category: '고기/구이',
    signatureMenu: '삼겹살, 전라도식 밑반찬',
    description: '넉넉한 전라도식 밑반찬과 질 좋은 삼겹살을 즐길 수 있는 로컬 맛집입니다.',
    locationInfo: '본사 후문 기준 도보 5분, 부영아파트 인근 상가',
    parking: '인근 도로 주차 가능',
    groupSeats: true,
    reservation: true,
    employeeReview: "반찬 가짓수에 놀라고 고기 맛에 두 번 놀랍니다. 팀 점심 회식으로 최고예요.",
    tags: ['팀점심', '삼겹살', '전라도식'],
    priceRange: '1~2만원',
    naverMapUrl: 'https://map.naver.com/v5/search/나주 부영식당'
  },
  {
    id: '3',
    name: '어나더키친',
    category: '양식',
    signatureMenu: '토마호크 스테이크, 파스타',
    description: '나주 호수공원 뷰를 바라보며 즐기는 스테이크와 파스타 분위기 맛집입니다.',
    locationInfo: '본사 정문 기준 도보 10분, 호수공원 전망 빌딩 2층',
    parking: '건물 지하 주차장',
    groupSeats: true,
    reservation: true,
    employeeReview: "창가 자리 뷰가 정말 예술입니다. 분위기 내고 싶은 날 추천드려요.",
    tags: ['호수공원뷰', '양식', '스테이크'],
    priceRange: '2~5만원',
    naverMapUrl: 'https://map.naver.com/v5/search/나주 어나더키친'
  },
  {
    id: '4',
    name: '나주곰탕 하얀집(혁신점)',
    category: '한식',
    signatureMenu: '나주곰탕, 수육',
    description: '나주의 상징과도 같은 곳으로, 맑고 깊은 국물이 일품인 곰탕 전문점입니다.',
    locationInfo: '본사 후문 기준 도보 6분, 빛가람동 중심 상권 위치',
    parking: '공영 주차장 이용 권장',
    groupSeats: true,
    reservation: false,
    employeeReview: "본점까지 갈 필요 없어요. 혁신점도 국물 맛이 깊고 해장에 딱입니다.",
    tags: ['해장', '필수코스', '나주곰탕'],
    priceRange: '1~2만원',
    naverMapUrl: 'https://map.naver.com/v5/search/나주곰탕 하얀집 혁신점'
  },
  {
    id: '5',
    name: '영산포홍어',
    category: '한식',
    signatureMenu: '홍어삼합, 홍어전',
    description: '톡 쏘는 홍어삼합의 진수를 맛볼 수 있는 곳으로, 타지 외빈 접대 시 로컬의 맛을 보여주기 좋습니다.',
    locationInfo: '본사 정문 기준 차량 5분, 빛가람동 외곽 위치',
    parking: '자체 주차장 보유',
    groupSeats: true,
    reservation: true,
    employeeReview: "홍어 제대로 하는 집입니다. 전라도 손맛을 제대로 보여주고 싶을 때 모셔갑니다.",
    tags: ['전라도손맛', '홍어', '로컬접대'],
    priceRange: '2~5만원',
    naverMapUrl: 'https://map.naver.com/v5/search/나주 영산포홍어'
  },
  {
    id: '6',
    name: '송현불고기',
    category: '고기/구이',
    signatureMenu: '돼지불고기',
    description: '불향 가득한 돼지불고기 단일 메뉴로 승부하는 강자입니다. 쌈 싸 먹는 재미가 쏠쏠합니다.',
    locationInfo: '본사 후문 기준 도보 7분, 먹자골목 내 위치',
    parking: '인근 유료 주차장',
    groupSeats: true,
    reservation: false,
    employeeReview: "불맛이 제대로 배어있어요. 메뉴 고민될 때 가면 무조건 성공하는 집입니다.",
    tags: ['가족식사', '불맛', '돼지불고기'],
    priceRange: '1~2만원',
    naverMapUrl: 'https://map.naver.com/v5/search/나주 송현불고기'
  },
  {
    id: '7',
    name: '태광갈비',
    category: '고기/구이',
    signatureMenu: '양념 돼지갈비, 냉면',
    description: '달콤한 양념 갈비와 깔끔한 냉면의 조화가 훌륭하며, 넓은 좌석으로 단체 회식에 적합합니다.',
    locationInfo: '본사 정문 기준 도보 5분, 파출소 인근 빌딩',
    parking: '건물 주차장 이용',
    groupSeats: true,
    reservation: true,
    employeeReview: "갈비 양념이 과하지 않고 맛있어요. 부서 회식 장소로 자주 애용합니다.",
    tags: ['저녁회식', '단체모임', '양념갈비'],
    priceRange: '2~5만원',
    naverMapUrl: 'https://map.naver.com/v5/search/나주 태광갈비'
  },
  {
    id: '8',
    name: '도담',
    category: '한식',
    signatureMenu: '보리굴비 정식, 한정식 코스',
    description: '정갈한 보리굴비 정식과 한정식 코스를 제공하여 비즈니스 미팅이나 격식 있는 자리에 좋습니다.',
    locationInfo: '본사 정문 기준 도보 8분, 조용한 상가 지역 위치',
    parking: '건물 앞 주차 가능',
    groupSeats: true,
    reservation: true,
    employeeReview: "보리굴비가 비리지 않고 고소해요. 조용한 분위기라 중요한 대화 나누기 좋습니다.",
    tags: ['비즈니스미팅', '격식', '보리굴비'],
    priceRange: '2~5만원',
    naverMapUrl: 'https://map.naver.com/v5/search/나주 도담 보리굴비'
  },
  {
    id: '9',
    name: '동명카츠',
    category: '일식',
    signatureMenu: '수제 등심 돈카츠',
    description: '겉바속촉 수제 돈카츠를 합리적인 가격에 즐길 수 있는 가벼운 한 끼 식사처입니다.',
    locationInfo: '본사 후문 기준 도보 3분, 본사 바로 앞 상가 1층',
    parking: '주차 협소',
    groupSeats: false,
    reservation: false,
    employeeReview: "혼밥하기 이보다 좋을 순 없죠. 가격도 착하고 고기도 두툼해서 자주 갑니다.",
    tags: ['혼밥', '가성비', '돈카츠'],
    priceRange: '1만원 이하',
    naverMapUrl: 'https://map.naver.com/v5/search/나주 동명카츠 혁신점'
  },
  {
    id: '10',
    name: '커피볶는집',
    category: '카페/디저트',
    signatureMenu: '핸드드립 커피, 수제 와플',
    description: '깊은 향의 커피와 여유로운 공간을 제공하여 식후 커피 브레이크나 가벼운 미팅에 좋습니다.',
    locationInfo: '본사 정문 기준 도보 4분, 메인 거리 위치',
    parking: '인근 도로 주차',
    groupSeats: true,
    reservation: false,
    employeeReview: "커피 향이 정말 진해요. 점심 먹고 팀원들이랑 수다 떨기 좋은 아지트 같은 곳입니다.",
    tags: ['카페', '커피브레이크', '여유'],
    priceRange: '1만원 이하',
    naverMapUrl: 'https://map.naver.com/v5/search/나주 커피볶는집'
  }
];
